== arc42

=== Where are the quality requirements documented in arc42?

In real-world systems we often find >100 different quality scenarios, way too many to digest all-at-once.

That’s why arc42 proposes to split those in two parts:
arc42 section 1.2 contains the high-priority quality requirements
arc42 section 10 contains the rest, structured as a quality tree.


Detailed answer: https://faq.arc42.org/questions/C-1-7/


=== What is meant by “constraints”? Can you give some examples?


Constraints restrict your freedom in decisions, concerning the system or any associated processes.

Such constraints are often imposed by organizations across multiple IT systems.

Examples:
System has to be operated by data-center XYZ, as our company has a long-term contract with them.
Part of software/hardware development has to be off-shored to our Asian subdivision.
Our operational database system needs to be IBM DB2.
System has to be implemented in Java.


Detailed answer: https://faq.arc42.org/questions/C-2-1/


=== What is the difference between the business context and the technical context context?

A short summary:
The business context concentrates an pure business or domain interactions of the system with its environment. You will often find domain terms for external interfaces, no technology.
The technical context shows hardware, technical infrastructure, technical protocols, network details or similar information concerning the system and its (technical) environment.


Detailed Answers:
https://faq.arc42.org/questions/C-3-2/
https://docs.arc42.org/tips/3-10/


=== What is meant by ‘Crosscutting Concepts’? Can you give some examples?

In short: instead of repeating recurring building-block substructures, factor those out into a crosscutting concepts.

Detailed: https://docs.arc42.org/tips/5-10/


=== Why is the glossary not optional?


You should ensure that all participating people have a common understanding of the important business (and technical) terminology which they use in context with the system.
The glossary is one manifestation of the general rule of “better explicit than implicit”.


Detailed: https://faq.arc42.org/questions/C-12-1/